### ISSUE TITLE
Small problem while opening a trace. 

### ISSUE THREAD

**Issue by alexandreborges** [anatolikalysch/VMAttack#1]
Dear developers, 

Good morning. How are you? 

I started to use this plugin and, at first time, everything seems having worked so well. However, today I had a small issue while opening a trace:

Python 2.7.6 (default, Nov 10 2013, 19:24:18) [MSC v.1500 32 bit (Intel)] 
## IDAPython v1.7.0 final (serial 0) (c) The IDAPython Team idapython@googlegroups.com

A Problem occured with the file selector dialog, first *.txt file in the current working directory was choosen!A Problem occured with the file selector dialog, first *.txt file in the current working directory was choosen!A Problem occured with the file selector dialog, first *.txt file in the current working directory was choosen!'NoneType' object is not iterable.

The image follows:

![image](https://cloud.githubusercontent.com/assets/13165245/19584275/fbfcb092-9721-11e6-900b-26868d873c09.png)

It is a small problem, but I thought that, eventually, you would like to know. In the other times, the dialog was perfectly shown. 

For workarounding it, I copied the trace file to the same directory of the obfuscated code (and IDA database). 

I hope you have a nice day and thank your for the attention.

Alexandre Borges.

**Comment by anatolikalysch** [comment]
Hello,

yes what you experienced was the fall-back solution, in case the file chooser dialog for the trace breaks down. Does the error persist? Or is the file chooser dialog working again?
