### ISSUE TITLE
vma_mgr Error

### ISSUE THREAD

**Issue by mendax47** [anatolikalysch/VMAttack#2]
While Opening a .NET Application Or DLL In The IDA Pro It Give Me A Error.... Looks Like This...

http://imgur.com/a/E5NHm

**Comment by anatolikalysch** [comment]
Does the error only occur on .net and .dll? Does the error persist if you disable other plug-ins?

**Comment by mendax47** [comment]
yah... it occur only on .net and .net dll... not for other...

**Comment by RaspyPiStyLiS** [comment]
When that happens for me is when I open another file in the same IDA window.
