### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'VMAttack_plugin_stub.py'

### ISSUE THREAD

**Issue by Waterman178** [anatolikalysch/VMAttack#3]
I installed python2.7.10 32bit and vmattack, but when I input the  ida plugin folder,it prompts an error IOError: [Errno 2] No such file or directory: 'VMAttack_plugin_stub.py'

C:\Users\Administrator>python D:\IDAPro6.6\VMAttack\setup.py install
[*] Starting dependency handling!
You are using pip version 7.0.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): distorm3 in c:\python27\lib\site-packages
You are using pip version 7.0.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): idacute in c:\python27\lib\site-packages
[*] Setting up environment and installing Plugin.

Success: The specified value has been saved.
Please input full path to the IDA *plugin* folder (e.g. X:\IDA\plugins\):  D:\IDAPro6.6\plugins\
Traceback (most recent call last):
  File "D:\IDAPro6.6\VMAttack\setup.py", line 58, in <module>
    copyfile(stub_name, ida_dir+stub_name)
  File "C:\Python27\Lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'VMAttack_plugin_stub.py'

**Comment by elwl** [comment]
If you run pip by itself to install distorm3, it tells you something about not being able to find vcvarsall.bat. 
Turns out you need to install https://www.microsoft.com/en-us/download/details.aspx?id=44266 . Worked fine for me using python 2.7.10.
