### ISSUE TITLE
Other install deps

### ISSUE THREAD

**Issue by elwl** [anatolikalysch/VMAttack#4]
The installer won't die, but theres an error message when trying to install distorm3. If you run pip by itself to install distorm3, it tells you something about not being able to find vcvarsall.bat. Turns out you need to install https://www.microsoft.com/en-us/download/details.aspx?id=44266 . 
Worked fine for me using python 2.7.10 windows 7 x64.
Might want to put this in the install instructions.

**Comment by anatolikalysch** [comment]
Thanks! Updated README.md
